version: "3.8"

services:
  besu-node1:
    build:
        context: .                
        dockerfile: Dockerfile
    working_dir: /app     
    image: besu-node
    container_name: besu-node1
    networks:
      besu-net:
        ipv4_address: 172.25.0.10
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: ["/app/start-node1.sh"]
    ports:
      - "8545:8545"
      - "30303:30303"
      - "9545:9545"
    volumes:
      - ./config:/app/config

  besu-node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    image: besu-node
    container_name: besu-node2
    networks:
      besu-net:
        ipv4_address: 172.25.0.11
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: ["/app/start-node2.sh"]
    ports:
      - "30304:30304"
      - "9546:9545"
    volumes:
      - ./config:/app/config


  besu-node3:
    build:
        context: .                
        dockerfile: Dockerfile
    working_dir: /app     
    image: besu-node
    container_name: besu-node3
    networks:
      besu-net:
        ipv4_address: 172.25.0.12
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: ["/app/start-node3.sh"]
    ports:
      - "30305:30305"
      - "9547:9545"
    volumes:
      - ./config:/app/config

      
  besu-node4:
    build:
        context: .                
        dockerfile: Dockerfile
    working_dir: /app     
    image: besu-node

    container_name: besu-node4
    networks:
      besu-net:
        ipv4_address: 172.25.0.13  
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: ["/app/start-node4.sh"]
    ports:
      - "30306:30306"
      - "9548:9545"
    volumes:
      - ./config:/app/config


  besu-node5:
    build:
        context: .                
        dockerfile: Dockerfile
    working_dir: /app     
    image: besu-node
    container_name: besu-node5
    networks:
      besu-net:
        ipv4_address: 172.25.0.14  
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: ["/app/start-node5.sh"]
    ports:
      - "30307:30307"
      - "9549:9545"
    volumes:
      - ./config:/app/config


  besu-node6:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app 
    image: besu-node
    container_name: besu-node6
    networks:
      besu-net:
        ipv4_address: 172.25.0.15  
    environment:
      - TZ=America/Sao_Paulo
    entrypoint: ["/app/start-node6.sh"]
    ports:
      - "30308:30308"
      - "9550:9545"
    volumes:
      - ./config:/app/config



networks:
  besu-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  config: